version: "3.8"
#
# Services definitions
#
services:
  app:
    image: kooldev/php:8.2-nginx
    container_name: "${COMPOSE_PROJECT_NAME}-app"
    ports:
      - "${KOOL_APP_PORT:-80}:80"
    environment:
      ASUSER: "${KOOL_ASUSER:-0}"
      UID: "${UID:-0}"
    volumes:
      - .:/app:delegated
    networks:
      - kool_local
      - kool_global
  database:
    image: mariadb:10.5
    container_name: "${COMPOSE_PROJECT_NAME}-db"
    ports:
      - ${KOOL_DATABASE_PORT:-3306}:3306
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD-rootpass}
    volumes:
      - ./docker/local:/docker-entrypoint-initdb.d
    networks:
      - kool_local
    ipc: host
    healthcheck:
      test: mysqladmin -p${DB_PASSWORD-pass} ping
  cache:
    image: redis:6-alpine
    container_name: "${COMPOSE_PROJECT_NAME}-cache"
    volumes:
      - cache:/data:delegated
    networks:
      - kool_local
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
  mailhog:
    image: mailhog/mailhog
    container_name: "${COMPOSE_PROJECT_NAME}-smtp"
    logging:
      driver: "none"
    ports:
      - "8004:1025"
      - "8101:8025"
    networks:
      - kool_local
    ipc: host
#
# Networks definitions
#
networks:
  kool_local:
  kool_global:
    external: true
    name: "${KOOL_GLOBAL_NETWORK:-kool_global}"
volumes:
  database:
  cache:
